---
AWSTemplateFormatVersion: '2010-09-09'
Description: "Create a base level security group set for IAM, and access configuration for the AWS account"
Resources:
  SysAdminRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - ec2.amazonaws.com
          Action:
          - sts:AssumeRole
  SysAdminProfile:
    Type: AWS::IAM::InstanceProfile
    DependsOn: SysAdminRole
    Properties:
      Path: "/"
      Roles:
      - !Ref SysAdminRole
  SysAdmin:
    Type: AWS::IAM::Group
    Properties:
      Path: "/"
  SysAdminPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          NotAction: iam:*
          Resource: "*"
          Condition:
            Bool:
              aws:MultiFactorAuthPresent: 'true'
        - Effect: Deny
          Action: aws-portal:*Billing
          Resource: "*"
        - Effect: Deny
          Action:
          - cloudtrail:DeleteTrail
          - cloudtrail:StopLogging
          - cloudtrail:UpdateTrail
          Resource: "*"
        - Effect: Deny
          Action:
          - kms:Create*
          - kms:Revoke*
          - kms:Enable*
          - kms:Get*
          - kms:Disable*
          - kms:Delete*
          - kms:Put*
          - kms:Update*
          Resource: "*"
      Roles:
      - Ref: SysAdminRole
      Groups:
      - Ref: SysAdmin
  IAMAdminGroup:
    Type: AWS::IAM::Group
    Properties:
      Path: "/"
  IAMAdminRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - ec2.amazonaws.com
          Action:
          - sts:AssumeRole
  IAMAdminProfile:
    Type: AWS::IAM::InstanceProfile
    DependsOn: IAMAdminRole
    Properties:
      Path: "/"
      Roles:
      - Ref: IAMAdminRole
  IAMAdminPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action: iam:*
          Resource: "*"
          Condition:
            Bool:
              aws:MultiFactorAuthPresent: 'true'
        - Effect: Deny
          Action: aws-portal:*Billing
          Resource: "*"
      Roles:
      - Ref: IAMAdminRole
      Groups:
      - Ref: IAMAdminGroup
  OpsGroup:
    Type: AWS::IAM::Group
    Properties:
      Path: "/"
  OpsRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - ec2.amazonaws.com
          Action:
          - sts:AssumeRole
  OpsProfile:
    Type: AWS::IAM::InstanceProfile
    DependsOn: OpsRole
    Properties:
      Path: "/"
      Roles:
      - Ref: OpsRole
  OpsPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Action: ec2:*
          Effect: Allow
          Resource: "*"
        - Effect: Allow
          Action: elasticloadbalancing:*
          Resource: "*"
        - Effect: Allow
          Action: cloudwatch:*
          Resource: "*"
        - Effect: Allow
          Action: autoscaling:*
          Resource: "*"
        - Effect: Deny
          Action:
          - ec2:CreateVpc*
          - ec2:DeleteVpc*
          - ec2:ModifyVpc*
          - ec2:CreateSubnet*
          - ec2:DeleteSubnet*
          - ec2:ModifySubnet*
          - ec2:Create*Route*
          - ec2:DeleteRoute*
          - ec2:AssociateRoute*
          - ec2:ReplaceRoute*
          - ec2:CreateVpn*
          - ec2:DeleteVpn*
          - ec2:AttachVpn*
          - ec2:DetachVpn*
          - ec2:CreateNetworkAcl*
          - ec2:DeleteNetworkAcl*
          - ec2:ReplaceNetworkAcl*
          - ec2:*Gateway*
          - ec2:*PeeringConnection*
          Resource: "*"
        - Effect: Deny
          Action: aws-portal:*Billing
          Resource: "*"
        - Effect: Deny
          Action:
          - kms:Create*
          - kms:Revoke*
          - kms:Enable*
          - kms:Get*
          - kms:Disable*
          - kms:Delete*
          - kms:Put*
          - kms:Update*
          Resource: "*"
      Roles:
      - Ref: OpsRole
      Groups:
      - Ref: OpsGroup
  ReadOnlyAdminGroup:
    Type: AWS::IAM::Group
    Properties:
      Path: "/"
  ReadOnlyAdminRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - ec2.amazonaws.com
          Action:
          - sts:AssumeRole
  ReadOnlyAdminProfile:
    Type: AWS::IAM::InstanceProfile
    DependsOn: ReadOnlyAdminRole
    Properties:
      Path: "/"
      Roles:
      - Ref: ReadOnlyAdminRole
  ReadOnlyAdminPolicy:
    Type: AWS::IAM::ManagedPolicy
    DependsOn: ReadOnlyAdminProfile
    Properties:
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Action:
          - appstream:Get*
          - autoscaling:Describe*
          - cloudformation:DescribeStacks
          - cloudformation:DescribeStackEvents
          - cloudformation:DescribeStackResource
          - cloudformation:DescribeStackResources
          - cloudformation:GetTemplate
          - cloudformation:List*
          - cloudfront:Get*
          - cloudfront:List*
          - cloudtrail:DescribeTrails
          - cloudtrail:GetTrailStatus
          - cloudwatch:Describe*
          - cloudwatch:Get*
          - cloudwatch:List*
          - directconnect:Describe*
          - dynamodb:GetItem
          - dynamodb:BatchGetItem
          - dynamodb:Query
          - dynamodb:Scan
          - dynamodb:DescribeTable
          - dynamodb:ListTables
          - ec2:Describe*
          - elasticache:Describe*
          - elasticbeanstalk:Check*
          - elasticbeanstalk:Describe*
          - elasticbeanstalk:List*
          - elasticbeanstalk:RequestEnvironmentInfo
          - elasticbeanstalk:RetrieveEnvironmentInfo
          - elasticloadbalancing:Describe*
          - elastictranscoder:Read*
          - elastictranscoder:List*
          - iam:List*
          - iam:Get*
          - kinesis:Describe*
          - kinesis:Get*
          - kinesis:List*
          - opsworks:Describe*
          - opsworks:Get*
          - route53:Get*
          - route53:List*
          - redshift:Describe*
          - redshift:ViewQueriesInConsole
          - rds:Describe*
          - rds:ListTagsForResource
          - s3:Get*
          - s3:List*
          - sdb:GetAttributes
          - sdb:List*
          - sdb:Select*
          - ses:Get*
          - ses:List*
          - sns:Get*
          - sns:List*
          - sqs:GetQueueAttributes
          - sqs:ListQueues
          - sqs:ReceiveMessage
          - storagegateway:List*
          - storagegateway:Describe*
          - trustedadvisor:Describe*
          Effect: Allow
          Resource: "*"
        - Effect: Deny
          Action: aws-portal:*Billing
          Resource: "*"
      Roles:
      - Ref: ReadOnlyAdminRole
      Groups:
      - Ref: ReadOnlyAdminGroup
  ReadOnlyBillingGroup:
    Type: AWS::IAM::Group
    Properties:
      Path: "/"
  ReadOnlyBillingPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action: aws-portal:View*
          Resource: "*"
        - Effect: Deny
          Action: aws-portal:*Account
          Resource: "*"
      Groups:
      - Ref: ReadOnlyBillingGroup
Outputs:
  SysAdmin:
    Value:
      Ref: SysAdmin
  IAMAdminGroup:
    Value:
      Ref: IAMAdminGroup
  OpsGroup:
    Value:
      Ref: OpsGroup
  ReadOnlyBillingGroup:
    Value:
      Ref: ReadOnlyBillingGroup
  ReadOnlyAdminGroup:
    Value:
      Ref: ReadOnlyAdminGroup
